environment:
  matrix:
    - nodejs_version: '10'
    - nodejs_version: '8'
    - nodejs_version: '6'

install:
  - npm i -g npm@latest
  - npm i

matrix:
  fast_finish: true

build: off

shallow_clone: true

test_script:
  - node --version
  - npm --version
  - npm run boot
  - npm run lint
  - npm test
